name: Developer checks
on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - spike/cypress
jobs:
    build:
        name: Attempt to build
        runs-on: ubuntu-latest
        # TODO Delete this
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm ci

            - name: Try to build
              run: npm run build

    lint:
        name: Lint codebase
        runs-on: ubuntu-latest
        # TODO Delete this
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

    await-deployment:
        # TODO Add: if: github.event_name == 'pull_request'
        name: Await vercel deployment
        runs-on: ubuntu-latest
        steps:
            - uses: SFDigitalServices/wait-for-deployment-action@v2
              id: deployment
              with:
                  github-token: ${{ github.token }}
                  environment: Preview
                  timeout: 120
            - name: Print
              run: echo "Deployed to ${{ steps.deployment.outputs.url }}"

    regression:
        # TODO Add: if: github.event_name == 'pull_request'
        name: Run regression tests
        runs-on: ubuntu-latest
        needs: await-deployment
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v4.2.1 # use the explicit version number
              with:
                  build: npm run build
                  start: npm start
                  CYPRESS_BASE_URL: https://dev.helbling.uk
