name: Build site

on:
    pull_request:
        branches:
            - develop

jobs:
    validate:
        name: Attempt to build
        runs-on: pineapple
        if: github.event_name == 'pull_request'
        steps:
            - name: Install dependencies
              run: npm ci
            - name: Install sharp
              run: npm install sharp
            - name: Try to build
              run: npm run build
