name: Developer checks
on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - spike/cypress
jobs:
    build:
        name: Attempt to build
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm ci

            - name: Try to build
              run: npm run build

    lint:
        name: Lint codebase
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

    await-deployment:
        runs-on: ubuntu-18.04
        steps:
            - name: Retrieve deployment URL (example on how to set an ENV var)
              run: "echo VERCEL_DEPLOYMENT_URL=nextjs-bzyss249z.vercel.app >> $GITHUB_ENV"

            - uses: UnlyEd/github-action-await-vercel@v1.2.14
              id: await-vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              with:
                  deployment-url: https://dev.helbling.uk
                  timeout: 10 # Wait for 10 seconds before failing
