name: Developer checks
on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - spike/cypress
jobs:
    build:
        name: Attempt to build
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm ci

            - name: Try to build
              run: npm run build

    lint:
        name: Lint codebase
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

    regression:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/vercel-cypress@v1
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  repo: portfolio

    # await-deployment:
    #     name: Wait for deployment
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: SFDigitalServices/wait-for-deployment-action@v2
    #           id: deployment
    #           with:
    #               token: ${{ github.token }}
    #               environment: Preview
    #         - name: Print
    #           run: echo "Deployed to ${{ steps.deployment.outputs.url }}"
