name: Developer checks
on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - spike/cypress
jobs:
    build:
        name: Attempt to build
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm ci

            - name: Try to build
              run: npm run build

    lint:
        name: Lint codebase
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

    await-deployment:
        runs-on: ubuntu-latest
        steps:
          - uses: SFDigitalServices/wait-for-deployment-action@v1
            id: deployment
            with:
              token: ${{ github.token }}
              environment: Preview
        - name: Wait on deployment
          run: echo "Deployed to: ${{ steps.deployment.outputs.url }}"
