name: Developer checks
on:
    push:
        branches-ignore:
            - develop
            - main
    pull_reqest:
        branches:
            - develop
            - main
jobs:
    build:
        name: Attempt to build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install typescript
              run: npm install --save-dev typescript @types/react @types/node

            - name: Try to build
              run: npm run build

    lint:
        name: Lint codebase
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ steps.extract_branch.outputs.branch }}

            - name: Install dependencies
              run: npm install --save-dev eslint

            - name: Lint
              run: npm run lint
