name: Main
on:
    pull_request:
        branches:
            - cicd
            - develop
jobs:
    docker:
        name: Push Docker Image
        runs-on: self-hosted
        if: github.event_name == 'pull_request'
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: helblingjoel/portfolio:latest

    restart:
        name: Redeploy
        runs-on: pineapple
        if: github.event_name == 'pull_request'
        steps:
            - name: Stop running container
              run: docker kill portfolio
            - name: Start container off latest
              run:
                  docker run -p 80:3000 443:3000 --name portfolio
                  helblingjoel/portfolio:latest
