name: Main
on:
    pull_request:
        branches:
            - cicd
jobs:
    docker_create_image:
        name: Create Docker Image
        runs-on: self-hosted
        if: github.event_name == 'pull_request'
        steps:

    docker:
        runs-on: self-hosted
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Build
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: helblingjoel/portfolio:latest
