name: Main
on:
    pull_request:
        branches:
            - main
            - develop

jobs:
    clean:
        name: Clean workspace
        runs-on: self-hosted
        if: github.event_name == 'pull_request'
        steps:
            - name: Tidy
              uses: AutoModality/action-clean@v1
    docker:
        name: Push Docker Image
        runs-on: self-hosted
        if: github.event_name == 'pull_request'
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: develop

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: helblingjoel/portfolio:latest

    restart:
        needs: docker
        name: Redeploy
        runs-on: pineapple
        if: github.event_name == 'pull_request'
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Stop running container
              run: docker stop portfolio || true && docker rm portfolio || true
            - name: Start container off latest
              run:
                  docker run -p 3000:3000 -d --name portfolio --restart unless-stopped -e
                  ${{ secrets.TWITTER_TOKEN }} helblingjoel/portfolio:latest
