name: Run test suite
on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - spike/cypress
jobs:
    regression:
        name: Run regression tests
        runs-on: ubuntu-latest
        needs: await-deployment
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cypress run
              uses: cypress-io/github-action@v4.2.1
              with:
                  build: npm run build
                  start: npm start
                  browser: chrome
                  wait-on: "http://localhost:3000"
